# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none

pool:
  vmImage: ubuntu-latest

variables:
  - group: WRKSHP_bch-modernize-apps
  - name: azureSubscription
    value: "WRKSHP_csa_sub_v2"
  - name: rgName
    value: "rg-bch-modernize-apps"
  - name: location
    value: "canadacentral"
  - name: deploymentName
    value: "bch-modernize-apps-deployment"
  - name: templateFilePath
    value: "$(System.DefaultWorkingDirectory)/infra/bicep/main.bicep"

stages:
  - stage: deployInfra
    jobs:
      - deployment: deployInfra
        environment: "WRKSHP_deployInfra"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  displayName: "Deploy Azure Resources"
                  inputs:
                    azureSubscription: "$(azureSubscription)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      az group create --name $(rgName) --location $(location)
                      # Deploy the Bicep template
                      # list contents of Bicep file
                      cat $(templateFilePath)
                      az deployment group create --resource-group $(rgName) \
                        --name $(deploymentName) \
                        --template-file $(templateFilePath) \
                        --parameters sqlAdminPassword=$(sqlAdminPassword)
